### ISSUE TITLE
Missing audio file.

### ISSUE THREAD

**Issue by shank885** [udacity/cd13698-Building-Image-and-Vision-Generative-AI-Solutions-on-Azure-course#1]
The audio file that is needed to generate the transcript by using the whisper model is not present in the repository.

**Comment by mayurmadnani** [comment]
Hey, firstly the audio file is optional. It is recommended to have it to have an end-to-end flow understanding. Here are the options for the project:

1. Record a small audio file using any voice recording tools to generate transcriptions using the Whisper model.
2. If you want to skip the audio file part of it, you can have the transcription file added directly as text file and write down the customer complaint directly.

Both options are acceptable.

**Comment by shank885** [comment]
Got it,
Thanks Mayur
